# Generated by Django 3.2.3 on 2022-05-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('desgination', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=230)),
                ('contact', models.CharField(max_length=250)),
            ],
        ),
    ]
